blank_issues_enabled: true
contact_links:
  - name: ğŸ“š é¡¹ç›®æ–‡æ¡£
    url: https://github.com/CaterpillarSoft/filter/blob/main/README.md
    about: æŸ¥çœ‹é¡¹ç›®æ–‡æ¡£è·å–æ›´å¤šä¿¡æ¯
  - name: ğŸ¤ è´¡çŒ®æŒ‡å—
    url: https://github.com/CaterpillarSoft/filter/blob/main/.github/CONTRIBUTING.md
    about: äº†è§£å¦‚ä½•ä¸ºé¡¹ç›®åšå‡ºè´¡çŒ®